name: Docker React
run-name: ${{ github.actor }} 🚀
on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t docker-react/docker-image:latest .

    - name: Push to Docker Hub
      run: docker push docker-react/docker-image:latest
     
        
